# Generated by Django 4.2.7 on 2025-12-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
