# Generated by Django 4.2.7 on 2025-12-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
